### ISSUE TITLE
Melee colors do not always trigger

### ISSUE THREAD

**Issue by jason-johnson** [weisluke/WoTMUD#26]
Any melee trigger which uses the capture will not currently work because multi-line capture is turned on which trashes the match variables.  If the multiline is turned off you don't actually need "very hard" and "extremely hard" because "hard" already catches all 3 cases.

**Comment by weisluke** [comment]
Turns out a specific one of the color highlights didn't work with multimatches. TIL.
Also, those triggers were written probably 5 years ago and 100% could be done better. I've slightly edited them to be better now, though there's still a couple spots for improvement (e.g. the duplication for very/extremely/hard messages as you pointed out). I'll fix those when I can confirm I've got the regex right that I need :p
