### ISSUE TITLE
Ability to change color scheme

### ISSUE THREAD

**Issue by jason-johnson** [weisluke/WoTMUD#27]
It would be nice to chose different colors for the various triggers.  The communications can be configured but e.g. melee is hard coded requiring the user to modify the settings themselves.  If the user modifies the settings themselves, will this not get overwritten if the user later does a `wotpack update`?

**Comment by weisluke** [comment]
I replied to this on discord but figured I'd finally do so here as well :P

The mapper and comms scripts are the ones that get updated most regularly, which is why I've spent time making them configurable. Things like the melee colors typically don't need anything else done to them. So once a user has them installed, they can edit the colors to their desire. 

For clarification on things, "wotpack update" will only update the package installer itself. "wotpack install mapper" would install the map scripts (downloading/installing whatever the most recent version on here is, so overriding any version you currently have installed). Yes, updating the melee colors would override any changes, but I would have to make updates to the melee colors worth pulling for that to be an issue...something which likely won't happen, as they're pretty one and done things (ok ok technically not as you found some issues with them which I've fixed, but other similar color triggers lie along this vein of thought)
